---
title: "Uma amostra de alunos do CCC"
output:
    html_document:
    df_print: paged
theme: sandstone
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
theme_set(theme_bw())

library(boot)
library(broom)

knitr::opts_chunk$set(tidy = FALSE,
                      fig.width = 6,
                      fig.height = 5)

```

```{r read}
dados = read_csv(here::here("data/amostra-alunos.csv"), 
                 ) 
dados = dados %>%
    rename(
        sono_semana = `Quantas horas por noite você dorme DURANTE A SEMANA em média?`,
        sono_fds = `Quantas horas por noite você dorme durante NO FIM DE SEMANA em média?`,
        disciplinas = `Quantas disciplinas você está cursando esse semestre?`,
        cafe = `Quantas xícaras de café você tomou ontem?`,
        segue_gh = `Quantas pessoas você segue no github?`,
        seguido_gh = `Quantas pessoas seguem você no github?`,
        quase_concluinte = `Você está dois períodos ou menos de concluir?`
    )
glimpse(dados)
```

```{r}
dados %>% 
    ggplot(aes(x = sono_semana)) + 
    geom_histogram(binwidth = 1)

dados %>% 
    ggplot(aes(x = sono_fds)) + 
    geom_histogram(binwidth = 1)
```




```{r}
theta_f = function(d, i){
    d %>% 
        slice(i) %>% 
        summarise(media_sono = mean(sono_semana)) %>% 
        pull(media_sono)
}

theta_c = theta_f(dados, 1:NROW(dados))
```

```{r}
dados %>% 
    boot(statistic = theta_f, R = 4000) %>% 
    tidy(conf.level = 0.95, 
         conf.int = TRUE)
```


```{r}
dados %>% 
    ggplot(aes(segue_gh, seguido_gh)) + 
    geom_point() + 
    geom_abline()
```

```{r}
dados %>% 
    summarise(correlacao = cor(segue_gh, seguido_gh))
```

```{r}
theta_f = function(d, i){
    d %>% 
        slice(i) %>% 
        summarise(correlacao = cor(segue_gh, seguido_gh)) %>% 
        pull(correlacao)
}

theta_c = theta_f(dados, 1:NROW(dados))
```

```{r}
dados %>% 
    boot(statistic = theta_f, R = 4000) %>% 
    tidy(conf.level = 0.95, 
         conf.int = TRUE)
```

----

```{r}
dados %>% 
    ggplot(aes(sono_semana, sono_fds)) + 
    geom_jitter(width = .1, height = .1) + 
    geom_abline()
```


```{r}
theta_semana = function(d, i){
    d %>% 
        slice(i) %>% 
        summarise(media_sono = mean(sono_semana)) %>% 
        pull(media_sono)
}

theta_fds = function(d, i){
    d %>% 
        slice(i) %>% 
        summarise(media_sono = mean(sono_fds)) %>% 
        pull(media_sono)
}


theta_semana(dados, 1:NROW(dados))
theta_fds(dados, 1:NROW(dados))
```

```{r}
dados %>% 
    boot(statistic = theta_semana, R = 4000) %>% 
    tidy(conf.level = 0.95, 
         conf.int = TRUE)
```

```{r}
dados %>% 
    boot(statistic = theta_fds, R = 4000) %>% 
    tidy(conf.level = 0.95, 
         conf.int = TRUE)
```

```{r}
theta_diferenca = function(d, i){
    d %>% 
        slice(i) %>% 
        summarise(media_sono = mean(sono_fds - sono_semana)) %>% 
        pull(media_sono)
}


theta_diferenca(dados, 1:NROW(dados))
```


```{r}
dados %>% 
    boot(statistic = theta_diferenca, R = 4000) %>% 
    tidy(conf.level = 0.95, 
         conf.int = TRUE)
```

---

```{r}
theta_segue = function(d, i){
    d %>% 
        slice(i) %>% 
        summarise(segue = mean(segue_gh)) %>% 
        pull(segue)
}

theta_seguido = function(d, i){
    d %>% 
        slice(i) %>% 
        summarise(seguido = mean(seguido_gh)) %>% 
        pull(seguido)
}


theta_segue(dados, 1:NROW(dados))
theta_seguido(dados, 1:NROW(dados))
```

```{r}
dados %>% 
    boot(statistic = theta_segue, R = 4000) %>% 
    tidy(conf.level = 0.95, 
         conf.int = TRUE)
```

```{r}
dados %>% 
    boot(statistic = theta_seguido, R = 4000) %>% 
    tidy(conf.level = 0.95, 
         conf.int = TRUE)

```

```{r}
theta_diferenca = function(d, i){
    segue = d %>% 
        slice(i) %>% 
        summarise(segue = mean(segue_gh)) %>% 
        pull(segue)
    
    seguido = d %>% 
        slice(i) %>% 
        summarise(seguido = mean(seguido_gh)) %>% 
        pull(seguido)
    
    segue - seguido
}


theta_diferenca(dados, 1:NROW(dados))
```

```{r}
dados %>% 
    boot(statistic = theta_diferenca, R = 4000) %>% 
    tidy(conf.level = 0.90, 
         conf.int = TRUE)
```

