---
title: "Interação"
output: html_notebook
---

```{r}
library(tidyverse)
library(htmlwidgets)
theme_set(theme_bw())

respostas = read_csv(here::here("data/enade-ccc-2017.csv"),
                     col_types = "cccdccdddc")

pb_pe = respostas %>% 
    filter(UF %in% c("PB", "PE"))
```

As bibliotecas que usaremos vêm de http://www.htmlwidgets.org

## Plotly

Veja também [esse tutorial](https://github.com/nazareno/ciencia-de-dados-1/blob/master/Tutoriais/tutorial_plotly.Rmd)

```{r}
library(plotly)

p = pb_pe %>% 
    mutate(texto = str_glue("{IES}\n{enunciado}\n{media}")) %>% 
    ggplot(aes(x = categoria, 
               y = media, 
               color = UF, 
               label = IES)) + 
    geom_point(size = 2, alpha = .5)  + 
    coord_flip() + 
    theme(legend.position = "None")
p
ggplotly(p)
```

```{r}
ggplotly(p, tooltip = "label")
```

----------

```{r}

```


```{r}
plot_ly(data = pb_pe %>% filter(categoria != "Outros"), 
        x = ~ categoria, 
        y = ~ media, 
        # name = "avaliacoes",
        type = "scatter",
        mode = "markers",
        color = ~UF, 
        text = ~IES)
```

