---
title: "Enade: Opiniões dos estudantes"
author: Iann Carvalho Barbosa, Júlio Guedes
date: "2 de maio de 2019"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(ggbeeswarm)
library(plotly)
library(flexdashboard)
library(htmlwidgets)
library(dplyr)
library(rgdal)
library(leaflet)
library(grid)
library(RColorBrewer)
library(gridExtra)
library(fmsb)
theme_set(theme_bw())

respostas = read_csv(here::here("data/enade-ccc-2017.csv"),
                     col_types = "cccdccdddc")

cursos = respostas %>% 
    group_by(UF) %>% 
    summarise(n = n(), 
              media = mean(media))

criterios = respostas %>% 
    group_by(UF, categoria) %>% 
    summarise(media = mean(media))

```

```{r}
sul = c("RS", "SC")
sudeste = c("SP", "RJ", "MG", "DF")
centro = c("GO")
norte = c("PR","AM")
nordeste = c("PI","PE","PB","MA","CE","BA")

melhores_ufs = respostas %>% 
    group_by(IES,UF) %>% 
    filter(categoria == "Curso em geral") %>% 
    summarise(n= mean(n), media= mean(media)) %>%
    arrange(desc(media))  %>%
    mutate(macrorregiao = case_when(
        UF %in% sul ~ "Sul",
        UF %in% sudeste ~ "Sudeste",
        UF %in% centro ~ "Centro-Oeste",
        UF %in% norte ~ "Norte",
        UF %in% nordeste ~ "Nordeste",
        TRUE ~ "Nenhum"),
        CD_GEOCUF = case_when(
            UF == "RS" ~ "43",
            UF == "SC" ~ "42",
            UF == "SP" ~ "35",
            UF == "RJ" ~ "33",
            UF == "MG" ~ "31",
            UF == "DF" ~ "53",
            UF == "GO" ~ "52",
            UF == "PR" ~ "15",
            UF == "AM" ~ "16",
            UF == "PI" ~ "22",
            UF == "PE" ~ "26",
            UF == "PB" ~ "25",
            UF == "MA" ~ "21",
            UF == "CE" ~ "23",
            UF == "BA" ~ "29"
        )
  )

melhores_macro = melhores_ufs %>%
    group_by(macrorregiao) %>%
    summarise(media = mean(media))
```

```{r}
criterios = criterios %>%
    mutate(macrorregiao = case_when(
        UF %in% sul ~ "Sul",
        UF %in% sudeste ~ "Sudeste",
        UF %in% centro ~ "Centro-Oeste",
        UF %in% norte ~ "Norte",
        UF %in% nordeste ~ "Nordeste",
        TRUE ~ "Nenhum"))

norte = criterios %>%
    filter(macrorregiao == "Norte") %>%
    group_by(categoria) %>%
    summarise(media = mean(media)) %>%
    spread(categoria, media)

nordeste = criterios %>%
    filter(macrorregiao == "Nordeste") %>%
    group_by(categoria) %>%
    summarise(media = mean(media)) %>%
    spread(categoria, media)

centro = criterios %>%
    filter(macrorregiao == "Centro-Oeste") %>%
    group_by(categoria) %>%
    summarise(media = mean(media)) %>%
    spread(categoria, media)

sul = criterios %>%
    filter(macrorregiao == "Sul") %>%
    group_by(categoria) %>%
    summarise(media = mean(media)) %>%
    spread(categoria, media)

sudeste = criterios %>%
    filter(macrorregiao == "Sudeste") %>%
    group_by(categoria) %>%
    summarise(media = mean(media)) %>%
    spread(categoria, media)
```

Column {data-width=650 .tabset .tabset-fade}
-----------------------------------------------------------------------

### Nordeste

```{r}
data=rbind(rep(5,5), rep(4,5), nordeste)

a = radarchart(data, axistype=1,
    pcol=rgb(1,0.5,0.3,0.9), pfcol=rgb(1,0.5,0.3,0.5), plwd=4, 
    cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(4,5,0.25), cglwd=0.8,
    vlcex=0.8)
```

### Norte

```{r}
data=rbind(rep(5,5), rep(4,5), norte)

a = radarchart(data, axistype=1,
    pcol=rgb(0.2,0.7,0.9,0.9), pfcol=rgb(0.2,0.7,0.9,0.5), plwd=4,
    cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(4,5,0.25), cglwd=0.8,
    vlcex=0.8)
```

### Centro-Oeste

```{r}
data=rbind(rep(5,5), rep(4,5), centro)

a = radarchart(data, axistype=1,
    pcol=rgb(0.5,0.6,0.7,0.9), pfcol=rgb(0.5,0.6,0.7,0.5), plwd=4,
    cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(4,5,0.25), cglwd=0.8,
    vlcex=0.8)
```

### Sul

```{r}
data=rbind(rep(5,5), rep(4,5), sul)

d = radarchart(data, axistype=1,
    pcol=rgb(0.8,0.9,0.1,0.9), pfcol=rgb(0.8,0.9,0.1,0.5), plwd=4,
    cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(4,5,0.25), cglwd=0.8,
    vlcex=0.8)

```

### Sudeste

```{r}
data=rbind(rep(5,5), rep(4,5), sudeste)

e = radarchart(data, axistype=1,
    pcol=rgb(0.9,0.8,0.8,0.8), pfcol=rgb(0.9,0.8,0.8,0.4), plwd=4,
    cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(4,5,0.25), cglwd=0.8,
    vlcex=0.8)
```

### Mapa

```{r, warning=FALSE, message=FALSE}
shp=readOGR(here::here("br/BRUFE250GC_SIR.shp"), stringsAsFactors=FALSE, encoding="UTF-8", verbose = FALSE)

new_shp = merge(shp,melhores_ufs, by = "CD_GEOCUF", duplicateGeoms = TRUE)

proj4string(new_shp) <- CRS("+proj=longlat +datum=WGS84 +no_defs")

Encoding(new_shp$NM_ESTADO) <- "UTF-8"

new_shp$media[is.na(new_shp$media)] <- 0

pal <- colorBin("Blues",domain = NULL,n=5) #cores do mapa

state_popup <- paste0("<strong>Estado: </strong>", 
                      new_shp$NM_ESTADO, 
                      "<br><strong>Média: </strong>", 
                      new_shp$media)
leaflet(data = new_shp) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(fillColor = ~pal(new_shp$media), 
              fillOpacity = 0.8, 
              color = "#BDBDC3", 
              weight = 1, 
              popup = state_popup)
```

Column {data-width=650}
-----------------------------------------------------------------------

### IES por categoria

```{r}
media_categorias <- respostas %>%
    group_by(IES, categoria) %>%
    summarise(media_cat = mean(media))
cursos_e_ufs <- unique(data.frame(IES = melhores_ufs$IES, UF = melhores_ufs$UF, macro = melhores_ufs$macrorregiao))

media_cursos <- merge(media_categorias, cursos_e_ufs, by="IES")

plot <- media_cursos %>%
    group_by(IES) %>%
    mutate(media_geral = mean(media_cat)) %>%
    ggplot(mapping = aes(x = categoria, y = media_cat,
                         color = macro,
                         text = paste("Instituição: ", IES, "\n",
                                      "Média na Categoria: ", media_cat, "\n",
                                      "Média Geral: ", media_geral, "\n",
                                      "UF: ", UF))) +
    geom_quasirandom() + 
    scale_color_brewer(palette = "Set1") +
    labs(x = "", y = "") + 
    theme(legend.position = "bottom")

ggplotly(plot, tooltip = c("text")) %>%
    layout(legend = list(
        orientation = "h",
        x = 0.15,
        y = -0.05
    ))
```


